---
exclude: '(^ext/|src/domain/_unit_tests/res/app.json)'
repos:
 - repo: https://github.com/ambv/black
   rev: 18.5b1
   hooks:
     - id: black
       args: [--line-length=120, --safe]
       python_version: python3.6
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v1.2.3
   hooks:
     - id: check-ast
     - id: check-symlinks
     - id: check-executables-have-shebangs
     - id: check-merge-conflict
     - id: check-json
     - id: check-xml
     - id: check-yaml
     - id: detect-aws-credentials
     - id: detect-private-key
     - id: flake8
       args: ['--config=setup.cfg']
     - id: end-of-file-fixer
     - id: trailing-whitespace
 - repo: https://github.com/Lucas-C/pre-commit-hooks
   rev: v1.1.5
   hooks:
     - id: forbid-crlf
       files: \.md$
     - id: remove-crlf
       files: \.md$
 - repo: local
   hooks:
     - id: remark
       name: remark
       entry: remark
       language: system
       files: \.(md)$
       args: ['-f']
